#!/usr/bin/python3

import sys
from common import *

def get_accounts_t4(msgs):
    accs = Counter()

    for msg in msgs:
        if isinstance(msg, Transfer):
            accs[msg.acc_from] += 1

    return accs

data, msgs = parse(sys.argv[1])
accs = get_accounts_t4(msgs)

# print(f"accounts: {accs}")
acc_mine, count = accs.most_common()[-1]
assert count == 1
# print(f"mine: {acc_mine}")

for msg in msgs:
    print(msg)

transaction = next(
    msg for msg in msgs 
    if isinstance(msg, Transfer) and msg.acc_from == acc_mine
)

transaction.acc_to, transaction.acc_from = transaction.acc_from, transaction.acc_to

with open("task4.out", 'wb+') as fil:
    res = b''.join(msg.encode() for msg in msgs)
    fil.write(res)