#!/usr/bin/python3

import sys
from common import *

data, msgs = parse(sys.argv[1])
accs = get_accounts(msgs)

for msg in msgs:
    print(msg)

# print(f"accounts: {accs}")
acc_mine = accs.most_common()[-1]
assert acc_mine[1] == 1
acc_mine = acc_mine[0]
# print(f"mine: {my_acc}")

transaction = next(msg for msg in msgs if isinstance(msg, Transfer) and msg.acc_to == acc_mine)

# print(vars(transaction))

with open("task2.out", 'wb+') as fil:
    res = data + transaction.encode()
    fil.write(res)
