#!/usr/bin/python3

import sys
from common import *
from copy import deepcopy


data, msgs = parse(sys.argv[1])
accs = get_accounts(msgs)
# print(f"accounts: {accs}")
acc_mine = accs.most_common()[-1]
assert acc_mine[1] == 1
acc_mine = acc_mine[0]
# print(f"mine: {my_acc}")

for msg in msgs:
    print(msg)

amounts = [
    msg.amount for msg in msgs
    if isinstance(msg, Transfer) or isinstance(msg, Invoice)
]
transaction = next(
    msg for msg in msgs 
    if isinstance(msg, Transfer) and msg.acc_to == acc_mine
)
other_amount = next(iter(set(amounts) - {transaction.amount}))
transaction.amount = other_amount

with open("task3.out", 'wb+') as fil:
    res = b''.join(msg.encode() for msg in msgs)
    fil.write(res)